course_catalog/config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  
  devise_for :users, controllers: { registrations: 'registrations' }
  
  get 'home', to: 'home#index'
  
  resources :courses do 
    member do 
      get :confirm_destroy
    end
  end
  resources :sections do
    member do 
      get :confirm_destroy
    end
  end
  resources :enrollments
  resources :grader_applications
  resources :recommendations

  namespace :admin do
    get 'index', to: 'admin#index'
    get 'reload_catalog', to: 'admin#reload_catalog'
    post 'reload_catalog', to: 'admin#reload_catalog'
    get 'approve', to: 'admin#approve'
    post 'users/:id/approve', to: 'admin#approve', as: 'approve_user'
  end

# Route for undefined paths
match '*path', to: 'application#not_found', via: :all
end

course_catalog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    # Add any logic needed for the home page
  end
end

course_catalog/app/views/home/index.html.erb
<div class="container">
  <h1>Welcome to the Course Catalog</h1>

  <% if user_signed_in? %>
    <p>Hello, <%= current_user.name %>!</p>
    <p>Your role is: <%= current_user.role %></p>
    <p>Your approval status is: <%= current_user.approved ? 'Approved' : 'Not Approved' %></p>

    <nav class="navigation-bar">
      <% if current_user.admin? %>
        <%= link_to 'Admin Dashboard', admin_index_path, class: "button" %>
      <% end %>
      <%= link_to 'Edit Profile', edit_user_registration_path, class: "button" %>
      <%= link_to 'View Courses', courses_path, class: "button" %>
      <%= link_to 'View Sections', sections_path, class: "button" %>

      <% if current_user.student? && current_user.approved? %>
      <%= link_to 'Grader Application', grader_applications_path, class: "button" %>
      <% end %>

      <% if current_user.instructor? %>
  <%= link_to 'Create Recommendation', new_recommendation_path, class: "button" %>
<% end %>
    </nav>

    <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "button" %>
  <% else %>
    <%= link_to 'Log in', new_user_session_path, class: "button" %>
    <%= link_to 'Sign up', new_user_registration_path, class: "button" %>
  <% end %>
</div>